# Generated by Django 3.1.7 on 2021-02-25 09:46

import colorfield.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dinastia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('lugar', models.CharField(blank=True, max_length=100, null=True)),
                ('color', colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Epoca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('img', models.URLField(max_length=255)),
                ('fecha_ini', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('ac_fini', models.BooleanField(default=False, verbose_name='Antes de cristo')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fallecimiento')),
                ('ac_ffin', models.BooleanField(default=False, verbose_name='Antes de cristo')),
                ('info', models.URLField(blank=True, max_length=255, null=True)),
                ('fecha_create', models.DateTimeField(default=datetime.datetime(2021, 2, 25, 10, 46, 20, 17833))),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.cargo')),
                ('dinastia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.dinastia')),
                ('madre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mama', to='web.persona')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papa', to='web.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_ini', models.DateField(blank=True, null=True, verbose_name='Fecha inicio')),
                ('ac_fini', models.BooleanField(default=False, verbose_name='Antes de cristo')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha final')),
                ('ac_ffin', models.BooleanField(default=False, verbose_name='Antes de cristo')),
                ('lugar', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('info', models.URLField(blank=True, max_length=255, null=True)),
                ('fecha_create', models.DateTimeField(default=datetime.datetime(2021, 2, 25, 10, 46, 20, 18447))),
                ('personas', models.ManyToManyField(to='web.Persona')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.tipoevento')),
            ],
        ),
    ]
