# Generated by Django 3.1.7 on 2021-02-28 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210228_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='epoca',
            name='ac_ffin',
            field=models.BooleanField(default=False, verbose_name='Antes de cristo'),
        ),
        migrations.AddField(
            model_name='epoca',
            name='ac_fini',
            field=models.BooleanField(default=False, verbose_name='Antes de cristo'),
        ),
        migrations.AddField(
            model_name='epoca',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha final'),
        ),
        migrations.AddField(
            model_name='epoca',
            name='fecha_ini',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha inicio'),
        ),
        migrations.AddField(
            model_name='epoca',
            name='siglo_fin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='epoca',
            name='siglo_inicio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 28, 12, 6, 47, 205907)),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 28, 12, 6, 47, 204637)),
        ),
    ]
