# Generated by Django 3.1.7 on 2021-02-28 11:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20210228_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 28, 12, 27, 36, 75254)),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 28, 12, 27, 36, 74108)),
        ),
        migrations.CreateModel(
            name='Relacion_Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=255)),
                ('persona1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona1', to='web.persona')),
                ('persona2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona2', to='web.persona')),
            ],
        ),
    ]
